title: Journey into code
author: Keith Hoffman
email: keithnhoffman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog documenting my journey to become computer literate, and my subsequent
  drive to go beyone the early "hello world" statements into the world of 
  data.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  khoffLSU # DO NOT include the @ character, or else the build will fail!

theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
